version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - nextcloud
      - line-backup-bot
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    environment:
      - OVERWRITEPROTOCOL=http
      - OVERWRITECLIURL=http://localhost:8081/nextcloud
      - OVERWRITEWEBROOT=/nextcloud
      - TRUSTED_PROXIES=nginx
      - NEXTCLOUD_SUBDIR=/nextcloud
    ports:
      - "8081:80"
    volumes:
      - ./nextcloud:/var/www/html
      - /media:/media:shared
    user: "www-data:www-data"
    restart: unless-stopped

  line-backup-bot:
    image: staravi/line_backup_bot:latest  # 請替換成你自己的 image 名稱
    container_name: line-backup-bot
    ports:
      - "8082:8080"
    environment:
      - CHANNEL_SECRET=<your-secret>
      - CHANNEL_ACCESS_TOKEN=<your-token>
      - SAVING_DIR=/app/storage
      # 其他必要設定...
    volumes:
      - <path-to-your-media>:/app/storage
    restart: unless-stopped
